name: librato
description: A Dart library to upload metrics data to librato.com.
version: 0.0.3
author: Devon Carew <devoncarew@google.com>
homepage: https://github.com/google/librato.dart
dependencies:
  crypto: '>=0.9.0 <0.10.0'
dev_dependencies:
  unittest: any
