name: librato
description: A Dart library to upload metrics data to librato.com.
version: 0.1.0
author: Devon Carew <devoncarew@google.com>
homepage: https://github.com/google/librato.dart
dev_dependencies:
  grinder: ^0.8.0
  test: ^0.12.0
